// Search CW4's IL2CPP interop assembly for a member by name, without launching
// the game.
//
//     dotnet run --project tools/reflect -- GetEff
//     dotnet run --project tools/reflect -- MYRANGE
//     dotnet run --project tools/reflect -- Cannon type
//
// Reads the game location from CW4_DIR, the same variable the shell harnesses
// use, and falls back to the maintainer's path.
//
// Prints the DECLARING TYPE and whether each hit is static, which is the part
// guesswork gets wrong. Two real examples, both of which had resisted an
// afternoon of guessing and fell out of one command here:
//
//   - ERNInterface has BOTH GetEff(int) (instance, feeds the UI) and
//     GetEfficiency(int) (STATIC, what the sim reads). Patching only the first
//     produced an upgrade that moved every number a probe could read and
//     nothing in the game.
//   - MYRANGE is declared per weapon type (Cannon, Mortar, Sniper, ...) and not
//     on UnitManager, so there is no base-class property to read.
//
// Metadata-only via MetadataLoadContext: nothing is executed, so the interop
// assemblies' dependency cascade is irrelevant. Do not reach for
// Assembly.LoadFrom in PowerShell instead - that stack-overflows on the resolve
// recursion.
using System;
using System.IO;
using System.Linq;
using System.Reflection;

class P {
    // The game directory, from CW4_DIR - the same override every shell harness
    // reads, so there is one variable to set rather than two conventions.
    //
    // THIS PATH USED TO BE HARD-CODED, twice, with no override at all: the
    // maintainer's own G: drive, written into the source. The tool compiled
    // everywhere and died at runtime on every other machine, and adding it to
    // the solution in this audit made that worse by building it for people who
    // then could not run it. The fallback keeps the maintainer's setup working
    // untouched; anyone else sets CW4_DIR.
    static string GameDir() {
        var dir = Environment.GetEnvironmentVariable("CW4_DIR");
        if (string.IsNullOrWhiteSpace(dir))
            dir = @"G:\Games\Steam\steamapps\common\Creeper World 4";
        return dir.TrimEnd('/', '\\');
    }

    static void Main(string[] a) {
        string game    = GameDir();
        string interop = Path.Combine(game, "BepInEx", "interop");
        string core    = Path.Combine(game, "BepInEx", "core");
        // Fail with the variable's NAME rather than a DirectoryNotFoundException
        // thrown from inside Directory.GetFiles, which says nothing actionable.
        if (!Directory.Exists(interop)) {
            Console.Error.WriteLine($"No BepInEx interop assemblies at {interop}");
            Console.Error.WriteLine("Set CW4_DIR to your Creeper World 4 install, e.g.");
            Console.Error.WriteLine(@"  CW4_DIR=D:\Steam\steamapps\common\Creeper World 4");
            Console.Error.WriteLine("They are generated by launching the game once with BepInEx installed.");
            Environment.Exit(1);
        }
        var files = Directory.GetFiles(interop, "*.dll").ToList();
        files.AddRange(Directory.GetFiles(core, "*.dll"));
        var rt = Directory.GetFiles(Path.GetDirectoryName(typeof(object).Assembly.Location), "*.dll");
        files.AddRange(rt);
        var res = new PathAssemblyResolver(files.Distinct());
        using var ctx = new MetadataLoadContext(res);
        var asm = ctx.LoadFromAssemblyPath(Path.Combine(interop, "Assembly-CSharp.dll"));
        string needle = a.Length > 0 ? a[0] : "GetEfficiency";
        string mode = a.Length > 1 ? a[1] : "method";
        foreach (var t in asm.GetTypes()) {
            try {
                if (mode == "ctor") {
                    if (t.Name.IndexOf(needle, StringComparison.OrdinalIgnoreCase) < 0) continue;
                    foreach (var c in t.GetConstructors(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)) {
                        var ps = string.Join(",", c.GetParameters().Select(x => x.ParameterType.Name + " " + x.Name));
                        Console.WriteLine($"CTOR {t.FullName}({ps})");
                    }
                    continue;
                }
                if (mode == "type") {
                    if (t.Name.IndexOf(needle, StringComparison.OrdinalIgnoreCase) >= 0)
                        Console.WriteLine("TYPE " + t.FullName);
                    continue;
                }
                // Everything ONE type declares. The name search above answers
                // "where does this member live"; this answers the opposite
                // question, "what does this type have", which is what you need
                // when you are looking for an identity or a persisted flag and
                // do not yet know what it would be called.
                if (mode == "members") {
                    if (!string.Equals(t.Name, needle, StringComparison.OrdinalIgnoreCase)) continue;
                    var bfm = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static
                            | BindingFlags.Instance | BindingFlags.DeclaredOnly;
                    Console.WriteLine("TYPE " + t.FullName + " : " + (t.BaseType?.Name ?? "-"));
                    foreach (var pr in t.GetProperties(bfm))
                        Console.WriteLine($"  PROP   {pr.Name} : {pr.PropertyType.Name}");
                    foreach (var f in t.GetFields(bfm)) {
                        if (f.Name.StartsWith("NativeFieldInfoPtr") ||
                            f.Name.StartsWith("NativeMethodInfoPtr")) continue;
                        Console.WriteLine($"  {(f.IsStatic ? "SFIELD" : "FIELD ")} {f.Name} : {f.FieldType.Name}");
                    }
                    foreach (var m in t.GetMethods(bfm)) {
                        if (m.Name.StartsWith("get_") || m.Name.StartsWith("set_")) continue;
                        var ps2 = string.Join(",", m.GetParameters().Select(x => x.ParameterType.Name));
                        Console.WriteLine($"  {(m.IsStatic ? "STATIC" : "METHOD")} {m.Name}({ps2}) -> {m.ReturnType.Name}");
                    }
                    continue;
                }
                var bf = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static
                       | BindingFlags.Instance | BindingFlags.DeclaredOnly;
                foreach (var m in t.GetMethods(bf)) {
                    if (m.Name.IndexOf(needle, StringComparison.OrdinalIgnoreCase) < 0) continue;
                    var ps = string.Join(",", m.GetParameters().Select(x => x.ParameterType.Name));
                    Console.WriteLine($"{(m.IsStatic ? "STATIC " : "       ")}{t.FullName}.{m.Name}({ps}) -> {m.ReturnType.Name}");
                }
                foreach (var f in t.GetFields(bf)) {
                    if (f.Name.IndexOf(needle, StringComparison.OrdinalIgnoreCase) < 0) continue;
                    Console.WriteLine($"{(f.IsStatic ? "SFIELD " : "FIELD  ")}{t.FullName}.{f.Name} : {f.FieldType.Name}");
                }
                foreach (var pr in t.GetProperties(bf)) {
                    if (pr.Name.IndexOf(needle, StringComparison.OrdinalIgnoreCase) < 0) continue;
                    bool st = pr.GetMethod?.IsStatic ?? false;
                    Console.WriteLine($"{(st ? "SPROP  " : "PROP   ")}{t.FullName}.{pr.Name} : {pr.PropertyType.Name}");
                }
            } catch {}
        }
    }
}
