"""Generate docs/randomizer-logic.md: what every mission and location requires.

Written because randomizer-design.md is a design NARRATIVE - it carries the
reasoning, the corrections and a section explicitly kept as "the discarded
approach" - and prose can drift from rules.py, which is what actually decides.
This reads rules.py and locations.py and emits a reference table, so the
document cannot disagree with the code that generated it.

Run from inside the Archipelago clone with the world synced in:
    python ../tools/audit/logictable.py
It writes docs/randomizer-logic.md in the repo.
"""
import io
import os
import sys

sys.path.insert(0, os.getcwd())

from worlds.cw4 import items as I, locations as L, opening as OP, roster as RO, rules as R  # noqa: E402

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, "docs", "randomizer-logic.md")


def fmt(groups) -> str:
    """An AND-of-ORs requirement as readable text."""
    if not groups:
        return "-"
    return " + ".join(
        " or ".join(sorted(group)) if len(group) > 1 else group[0]
        for group in groups
    )


def main() -> int:
    out = []
    w = out.append

    w("# Randomizer logic reference")
    w("")
    w("GENERATED by `tools/audit/logictable.py` from `apworld/cw4/rules.py`. "
      "Do not hand-edit - re-run the generator.")
    w("Do not hand-edit: re-run it instead. This exists because")
    w("[randomizer-design.md](randomizer-design.md) is the design narrative -")
    w("reasoning, corrections and one section kept deliberately as the discarded")
    w("approach - and prose drifts from the code that actually decides.")
    w("")
    w("`A + B` means both are needed. `A or B` means either satisfies it.")
    w("Requirements are what the STANDARD logic tier assumes; the `casual` column")
    w("shows where that tier asks for more.")
    w("")
    # EASY GETS A SENTENCE, NOT A COLUMN, and the sentence is checked rather than
    # trusted - a column of "same as casual but four items" on 900 rows would
    # say less than one line that is enforced. Before EASY_FULL_FROM easy must
    # equal casual exactly. From it, every check casual touches easy must touch
    # too; easy may touch MORE, where standard already asks for one anti-air
    # unit (The Compound's Sniper) so casual's either-or adds nothing and easy's
    # four do. Those are named rather than hidden - an earlier version of this
    # said "exactly the same checks" and this guard proved it false.
    every = [(name, n) for n in tuple(range(1, 21)) + L.SPAN_MISSION_NUMBERS
             for name in L.location_names_for_mission(n)]
    also = []
    for name, n in every:
        std = R.location_requirements(name, n, casual=R.LOGIC_STANDARD)
        cas = R.location_requirements(name, n, casual=R.LOGIC_CASUAL)
        easy = R.location_requirements(name, n, casual=R.LOGIC_EASY)
        if n < R.EASY_FULL_FROM and easy != cas:
            raise SystemExit(f"easy differs from casual at {name}, before "
                             f"mission {R.EASY_FULL_FROM}; the sentence below "
                             f"would be false")
        if cas != std and easy == std:
            raise SystemExit(f"casual adds to {name} and easy does not; the "
                             f"sentence below would be false")
        if easy != std and cas == std:
            also.append(I.ALL_MISSION_TITLES[n])
    also = sorted(set(also))
    w(f"The `easy` tier is casual until {I.ALL_MISSION_TITLES[R.EASY_FULL_FROM]} "
      f"(mission {R.EASY_FULL_FROM}). From there it asks for "
      f"{' + '.join(R.EASY_DEFENSE)} where casual asks for "
      f"{' or '.join(R.DEFENSIVE)}: on every check the `casual` column changes"
      + (f", and also on {', '.join(also)}, where standard already asks for one "
         f"anti-air unit so casual adds nothing." if also else "."))
    w("")

    # --- per mission -----------------------------------------------------
    w("## What each mission requires")
    w("")
    w("To COMPLETE the mission, which is what gates its Mission Complete check")
    w("and counts toward the finale.")
    w("")
    w("| # | Mission | Standard | Casual |")
    w("|---|---|---|---|")
    for n in range(1, 21):
        std = fmt(R.mission_requirements(n, casual=False))
        cas = fmt(R.mission_requirements(n, casual=True))
        w(f"| {n} | {L.MISSION_TITLES[n]} | {std} | "
          f"{'same' if cas == std else cas} |")
    w("")
    w("### The SPAN Experiments")
    w("")
    w("Off by default (`span_missions`), and the rows below are DERIVED rather")
    w("than played - read them as a floor, not as the truth. Every campaign")
    w("requirement above traces to somebody finishing that mission and saying")
    w("what they needed; these trace to a measurement taken on an empty map,")
    w("which cannot see creep advance, non-terrain reach or environmental")
    w("hazards. See docs/design/span-requirements-worksheet.md.")
    w("")
    w("| # | Mission | Standard | Casual |")
    w("|---|---|---|---|")
    for n in L.SPAN_MISSION_NUMBERS:
        std = fmt(R.mission_requirements(n, casual=False))
        cas = fmt(R.mission_requirements(n, casual=True))
        w(f"| {n} | {I.ALL_MISSION_TITLES[n]} | {std} | "
          f"{'same' if cas == std else cas} |")
    w("")

    # --- per location ----------------------------------------------------
    w("## What each check requires")
    w("")
    w("Every check, in mission order. A location entry is COMPLETE - the")
    w("mission's own requirements are folded in, except where a per-instance")
    w("waiver deliberately drops them (a free first cache, say).")
    w("")
    for n in tuple(range(1, 21)) + L.SPAN_MISSION_NUMBERS:
        names = L.location_names_for_mission(n)
        if not names:
            continue
        w(f"### {n}. {I.ALL_MISSION_TITLES[n]}")
        w("")
        w("| Check | Standard | Casual |")
        w("|---|---|---|")
        for name in names:
            std = fmt(R.location_requirements(name, n, casual=False))
            cas = fmt(R.location_requirements(name, n, casual=True))
            short = name.split(" - ", 1)[1] if " - " in name else name
            w(f"| {short} | {std} | {'same' if cas == std else cas} |")
        w("")

    # --- placement -------------------------------------------------------
    w("## What is placed early, and what is not")
    w("")
    w("Logic decides what is REACHABLE. These decide what is placed WHERE, and")
    w("they are separate - a taste in pacing does not belong in logic, because a")
    w("rule saying a mission needs a mortar specifically would be false wherever")
    w("a cannon also works.")
    w("")
    w("**Free at the start, with no item at all**")
    w("")
    w(f"- {len(RO.STARTER_ELIGIBLE)} missions are starter-eligible; "
      "`starter_missions` (default 2, range 2 to 6) of them open unlocked.")
    w("  Eligible: " + ", ".join(L.MISSION_TITLES[n] for n in sorted(RO.STARTER_ELIGIBLE)))
    w("- They are drawn at random per seed, and get no unlock item, which is why")
    w("  a default seed has 18 mission unlocks rather than 20.")
    w("")
    w("**Pulled early on purpose, via `local_early_items`**")
    w("")
    w("- One weapon: whichever of Cannon and Mortar `early_weapon` names")
    w("  (default `random`, resolved per seed). LOCAL rather than `early_items`,")
    w("  because Archipelago may satisfy `early_items` in another player's world,")
    w("  which does nothing for an opening that has to chain through ours.")
    w("- One extra mission unlock. When no starter opens up under a weapon it")
    w("  is drawn from missions that do; otherwise the choice stays uniform, so")
    w("  openings stay varied.")
    w("- Both land in the locations reachable holding nothing. When every player")
    w("  is Creeper World 4 our own fill places them, because it runs before")
    w("  Archipelago's early-items step; with another game present Archipelago")
    w("  does. An opening one location wide requests only the unlock.")
    w(f"- When every player is Creeper World 4 and the opening is narrower than")
    w(f"  the fill can risk, a bootstrap replaces both requests: it places items")
    w(f"  itself until {OP.SAFE_OPENING} locations are free, drawn only from items")
    w("  that actually open something, the requested weapon first when it does.")
    w("")
    w("**Everything else is the ordinary fill**")
    w("")
    w("- Traps, ERN port upgrades, ERN surges, energy storage, base generation")
    w("  and the boons have no placement logic whatsoever.")
    w("- Our own progression items are placed by Archipelago's `fill_restrictive`")
    w("  as well - we only call it ourselves so we can RETRY it. Its backtracking")
    w("  is capped at two swaps per item, which failed about once in 18,000 seeds.")
    w("  Same algorithm, same randomness.")
    w("")
    w("**Never required by any rule**")
    w("")
    # UNIT_ITEMS alone misses BONUS_UNIT_ITEMS - Airship, Bertha and Sweeper,
    # the three the campaign never grants - and those are exactly the ones most
    # likely to be unrequired, so leaving them out would hide the answer.
    all_units = list(I.UNIT_ITEMS) + list(I.BONUS_UNIT_ITEMS)
    never = sorted(
        name for name in all_units
        if not any(
            name in group
            for n in tuple(range(1, 21)) + L.SPAN_MISSION_NUMBERS
            for loc in L.location_names_for_mission(n)
            for group in R.location_requirements(loc, n, casual=True)
        )
    )
    w("- " + ", ".join(never) if never else "- (none)")
    w("")
    w("  Nothing in logic asks for these, so they can land anywhere, including")
    w("  the final sphere.")
    w("")

    text = "\n".join(out) + "\n"
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print("wrote %s (%d lines)" % (OUT, len(out)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
