"""SPAN Experiment mission data - GENERATED by tools/gen_spandata.py.

Do not hand-edit. Re-run the generator against the survey dumps.

MISSION NUMBERS 21..46 ARE FROZEN. Location ids are positional, so
reordering SPAN_ORDER in the generator renumbers every SPAN location and
breaks seeds in flight. Append, never insert.

Every number here was measured, not authored - see
docs/design/span-survey.md and docs/design/span-requirements.md for how,
and what each measurement can and cannot support.
"""

FIRST_SPAN_MISSION = 21

# mission -> (guid, title). The guid IS the launch specifier: verified by
# booting all 26, specifier == guid on every one.
SPAN_MISSIONS = {
    21: ('knucracker1', 'Forgotten Fortress'),
    22: ('knucracker2', 'Four Pieces'),
    23: ('knucracker3', 'Neuron'),
    24: ('knucracker4', 'Creeper++'),
    25: ('knucracker5', 'Turtle'),
    26: ('knucracker6', 'Valley of the Shadow of Death'),
    27: ('knucracker7', 'Parasite'),
    28: ('knucracker8', 'Cheap Construction'),
    29: ('knucracker9', 'Sector L'),
    30: ('knucracker10', 'Gort'),
    31: ('knucracker11', 'Creepers Pieces'),
    32: ('knucracker12', 'Special'),
    33: ('knucracker13', 'Highway to helheim'),
    34: ('knucracker14', 'Creeperpeace'),
    35: ('knucracker15', 'Islands'),
    36: ('knucracker16', 'Enchanted Forest'),
    37: ('knucracker17', 'The Dark Side'),
    38: ('knucracker18', 'Far York Farm'),
    39: ('knucracker19', 'Chanson'),
    40: ('knucracker20', 'Invasion'),
    41: ('knucrackerbonus0', 'Razor'),
    42: ('knucrackerbonus1', 'Holdem 2'),
    43: ('demobonus', 'Mark V Sample'),
    44: ('demobonus2', 'Before Time'),
    45: ('demobonus3', 'Day of Infamy'),
    46: ('demobonus4', 'Shaka'),
}

# mission -> (caches, totems, nullifiable), counted off the live map.
SPAN_INSTANCE_COUNTS = {
    21: (0, 4, 5),
    22: (0, 4, 5),
    23: (0, 2, 8),
    24: (0, 3, 4),
    25: (0, 11, 4),
    26: (0, 2, 6),
    27: (0, 10, 2),
    28: (0, 3, 6),
    29: (0, 3, 5),
    30: (0, 2, 4),
    31: (0, 3, 5),
    32: (0, 1, 4),
    33: (0, 2, 5),
    34: (0, 3, 6),
    35: (0, 3, 4),
    36: (0, 3, 5),
    37: (0, 2, 13),
    38: (1, 3, 7),
    39: (0, 4, 10),
    40: (0, 3, 8),
    41: (0, 6, 9),
    42: (0, 2, 8),
    43: (0, 4, 6),
    44: (0, 3, 8),
    45: (0, 4, 8),
    46: (0, 5, 8),
}

# mission -> enabled objective slots. Hold (slot 3) is DELIBERATELY
# dropped: no Farsite mission uses it and locations.py has no location
# for it, so creating one would be a silent model change.
SPAN_OBJECTIVE_SLOTS = {
    21: [0, 1, 2],  # Nullify, Totems, Reclaim
    22: [0, 1, 2],  # Nullify, Totems, Reclaim
    23: [0, 1, 2],  # Nullify, Totems, Reclaim
    24: [0, 1, 2],  # Nullify, Totems, Reclaim
    25: [0, 1],  # Nullify, Totems
    26: [0, 1, 2],  # Nullify, Totems, Reclaim
    27: [0, 1, 2],  # Nullify, Totems, Reclaim
    28: [0, 1, 2],  # Nullify, Totems, Reclaim
    29: [0, 1, 2],  # Nullify, Totems, Reclaim
    30: [0, 1, 2],  # Nullify, Totems, Reclaim
    31: [0, 1, 2],  # Nullify, Totems, Reclaim
    32: [0, 1, 2],  # Nullify, Totems, Reclaim
    33: [0, 1, 2],  # Nullify, Totems, Reclaim
    34: [0, 1, 2],  # Nullify, Totems, Reclaim
    35: [0, 1, 2],  # Nullify, Totems, Reclaim
    36: [0, 1, 2],  # Nullify, Totems, Reclaim
    37: [0, 1, 2],  # Nullify, Totems, Reclaim
    38: [0, 1, 2],  # Nullify, Totems, Reclaim
    39: [0, 1, 2, 5],  # Nullify, Totems, Reclaim, Custom
    40: [0, 1, 2],  # Nullify, Totems, Reclaim
    41: [0, 1, 2],  # Nullify, Totems, Reclaim
    42: [0, 1, 2],  # Nullify, Totems, Reclaim
    43: [0, 1],  # Nullify, Totems
    44: [0, 1],  # Nullify, Totems
    45: [0, 1, 2],  # Nullify, Totems, Reclaim
    46: [0, 1, 2],  # Nullify, Totems, Reclaim
}

# mission -> does the Factory gate its totems?
#
# A ware is free when a Pod on the map carries it and must otherwise be
# made in the Factory - the same rule for every ware. Liftic is ware30,
# Arg is ware29; the campaign only ever uses Liftic, so the Arg maps have
# no campaign precedent and are marked below.
SPAN_TOTEMS_NEED_FACTORY = {
    21: True,  # wants Liftic, no pods on the map
    22: True,  # wants Liftic, no pods on the map
    23: True,  # wants Liftic, no pods on the map
    24: True,  # wants Liftic, no pods on the map
    25: True,  # wants Arg/Liftic, no pods on the map
    26: True,  # wants Arg, no pods on the map
    27: True,  # wants Arg, no pods on the map
    28: True,  # wants Liftic, no pods on the map
    29: True,  # wants Liftic, no pods on the map
    30: True,  # wants Liftic, no pods on the map
    31: True,  # wants Liftic, no pods on the map
    32: True,  # wants Liftic, no pods on the map
    33: True,  # wants Liftic, no pods on the map
    34: True,  # wants Liftic, no pods on the map
    35: True,  # wants Liftic, no pods on the map
    36: True,  # wants Liftic, no pods on the map
    37: True,  # wants Liftic, no pods on the map
    38: True,  # wants Liftic, no pods on the map
    39: True,  # wants Liftic, no pods on the map
    40: True,  # wants Liftic, no pods on the map
    41: True,  # wants Liftic, no pods on the map
    42: True,  # wants Liftic, no pods on the map
    43: False,  # wants Liftic, Liftic
    44: False,  # wants Liftic, Liftic
    45: False,  # wants Liftic, Liftic
    46: True,  # wants Arg, no pods on the map
}

# mission -> a mover is needed for some of its objectives.
#
# Objective-WIDE, not per instance. The analysis says which objectives
# share a component; turning that into "this one needs a mover" needs
# the landing site, and no rift lab exists at mission load to read it
# from. Requiring it of the whole objective over-constrains rather than
# under-constrains, which is the safe direction.
SPAN_NEEDS_MOVER = {
    31,  # Creepers Pieces
    33,  # Highway to helheim
    40,  # Invasion
}

# Maps carrying something the model does not express. Recorded rather
# than silently dropped.
SPAN_NOTES = {
    24: 'Hold/Survive objective present; no location is created for it',
    41: 'Hold/Survive objective present; no location is created for it',
    42: 'Hold/Survive objective present; no location is created for it',
    46: 'Hold/Survive objective present; no location is created for it',
}

