"""Turn an instance dump into the mod's MapCells table.

Cache positions are MAP data: they do not change with a save, a seed or a
playthrough. That makes the cell a perfectly good identity for a cache - the
problem was never the id, it was that a COLLECTED cache is destroyed, so the
live scene can only list what is LEFT.

The first fix recorded the intact set the first time the mod saw a mission
(SlotState.CacheCells). That works but is weaker than it needs to be: it cannot
help a save whose caches were taken before the mod was ever installed, because
by then the full set has never been observed. Since the set is fixed map data,
the mod can just KNOW it. This generates that table from a dump.

    bash tools/instance-dump.sh "$(cat missions.txt)"     # all 20 missions
    python tools/gen-mapcells.py

Instance order is (cellY, cellX) ascending, the same rule as
InstanceIndex.Assign - computed here so the two cannot drift apart by hand.
"""
import io
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DUMP = os.path.join(REPO, '.aptest', 'instance-dump.txt')
OUT = os.path.join(REPO, 'src', 'CW4Archipelago.Core', 'MapCells.cs')


def parse(path):
    """{mission: {kind: [(x, y), ...]}} keyed off the GAME's own block marker.

    Deliberately not the harness's "===== first storyN (Title)" header. That
    header carries a title read from a caller-supplied list, and a CRLF list put
    a carriage return inside it - which Python's splitlines() treats as a line
    break, so every header parsed as two lines, no mission was ever identified,
    and all 22 caches were attributed to the last block standing. The game's own
    "INST DUMP: mission=storyN" line has nothing interpolated into it.

    The FIRST block for a mission wins: the harness deliberately boots Shattered
    twice for its determinism check, and re-boots Farsite for the cache-identity
    phase where one cache has already been taken. A later, shorter block must
    not overwrite the intact one.
    """
    text = io.open(path, encoding='utf-8').read()
    missions = {}
    current = None
    for raw in text.splitlines():
        line = raw.strip()
        head = re.match(r'^INST DUMP: mission=story(\d+)', line)
        if head:
            n = int(head.group(1))
            current = None if n in missions else n
            if current is not None:
                missions[current] = {'NULLIFY': [], 'TOTEM': [], 'CACHE': []}
            continue
        # A block ends at the harness's own separator, so the cache-identity
        # phase's stray INST CACHE lines cannot land on the previous mission.
        if line.startswith('====='):
            current = None
            continue
        if current is None:
            continue
        m = re.match(r'^INST (NULLIFY|TOTEM|CACHE) raw=\d+ cell=\((-?\d+),(-?\d+)\)', line)
        if m:
            missions[current][m.group(1)].append((int(m.group(2)), int(m.group(3))))
    return missions


def ordered(cells):
    """Instance order: (Y, X) ascending. Must match InstanceIndex.Assign."""
    return sorted(cells, key=lambda c: (c[1], c[0]))


def main():
    if not os.path.exists(DUMP):
        sys.exit('no dump at %s - run tools/instance-dump.sh first' % DUMP)
    missions = parse(DUMP)
    if not missions:
        sys.exit('dump parsed to nothing - has the format changed?')

    caches = {}
    for n in sorted(missions):
        cells = ordered(missions[n]['CACHE'])
        if cells:
            caches[n] = cells

    # Any cell the dump could not read makes the whole mission unusable: a
    # partial row would silently shift every index after the gap.
    for n, cells in list(caches.items()):
        if any(x < 0 or y < 0 for x, y in cells):
            print('  SKIP story%d - unreadable cell in the dump' % n)
            del caches[n]

    body = []
    for n in sorted(caches):
        entries = ', '.join('"%d,%d"' % (x, y) for x, y in caches[n])
        body.append('        [%d] = new[] { %s },' % (n, entries))

    src = '''using System.Collections.Generic;

namespace CW4Archipelago.Core;

/// <summary>
/// Where a mission's caches ARE, in instance order.
///
/// GENERATED by tools/gen-mapcells.py from tools/instance-dump.sh. Do not edit
/// by hand - regenerate, so the ordering rule stays the same one
/// InstanceIndex.Assign uses.
///
/// This exists because caches are the one counted objective whose instances
/// cannot be identified from live state. A nullified structure keeps standing
/// wearing IsSuppressed() and a finished totem keeps totemComplete, so both can
/// be named at any time. A collected cache is DESTROYED - measured on Farsite,
/// mustCollect 2 to 1 and the InfoCache objects in the scene 2 to 1 - and
/// UnitManager carries no id of its own, so there is nothing left to ask.
///
/// The cell IS a stable identity, though, and cache positions are MAP data:
/// they do not vary with a save, a seed or a playthrough. So rather than
/// discovering the intact set the first time the mod happens to see a mission,
/// which cannot help a save whose caches were taken before the mod was
/// installed, the set is simply known. Collected = known minus remaining.
///
/// If a game update ever moves a cache this table goes stale, which is why the
/// caller checks that what is still on the map is a SUBSET of the row before
/// trusting it, and falls back to the observed set otherwise.
/// </summary>
public static class MapCells
{
    private static readonly Dictionary<int, string[]> CacheCells = new()
    {
%s
    };

    /// <summary>A mission's cache cells in instance order, or null if unknown.</summary>
    public static IReadOnlyList<string>? CachesFor(int mission)
        => CacheCells.TryGetValue(mission, out var cells) ? cells : null;

    /// <summary>Whether every cell still on the map appears in the table. False
    /// means the table cannot be trusted for this mission - a moved cache, a
    /// modded map - and the caller must fall back rather than mislabel.</summary>
    public static bool Covers(int mission, IEnumerable<string> present)
    {
        var known = CachesFor(mission);
        if (known == null)
            return false;
        var set = new HashSet<string>(known);
        foreach (var p in present)
            if (!set.Contains(p))
                return false;
        return true;
    }
}
''' % '\n'.join(body)

    io.open(OUT, 'w', encoding='utf-8', newline='\n').write(src)
    print('wrote %s' % OUT)
    print('missions with caches: %d' % len(caches))
    for n in sorted(caches):
        print('  story%-3d %s' % (n, ' '.join('(%d,%d)' % c for c in caches[n])))


if __name__ == '__main__':
    main()
