"""Emit the C# side of the SPAN mission table from apworld/cw4/span_data.py.

GENERATED RATHER THAN HAND-WRITTEN because the same 26 maps are described on
both sides of the wire and the two must not drift. The apworld builds location
names from its titles; the plugin resolves a running map back to a mission by
its guid and then builds the SAME names to send the checks. A title that differs
by one character sends a location the server has never heard of, and the check
is silently lost.

Usage:
    py -3.13 tools/gen-spancsharp.py
Writes src/CW4Archipelago.Core/SpanMissionTable.g.cs and prints what changed.
"""
import io
import os
import runpy
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'apworld', 'cw4', 'span_data.py')
DST = os.path.join(ROOT, 'src', 'CW4Archipelago.Core', 'SpanMissionTable.g.cs')

data = runpy.run_path(SRC)
missions = data['SPAN_MISSIONS']
counts = data['SPAN_INSTANCE_COUNTS']
slots = data['SPAN_OBJECTIVE_SLOTS']


def cs_string(s):
    if '"' in s or '\\' in s:
        sys.exit('title needs escaping, which this generator does not do: %r' % s)
    return '"%s"' % s


def objectives(n):
    """Which objective slots the MAP contains - the same question
    MissionRules.MissionObjectives answers for the campaign.

    Counted objectives come from the instance counts (a map with zero totems has
    no Totems objective however its slots are configured); Reclaim and Custom
    come from the enabled slots, since neither is counted. Hold is absent from
    SPAN_OBJECTIVE_SLOTS by construction, so it can never appear here.
    """
    caches, totems, nullifiable = counts[n]
    found = []
    if nullifiable:
        found.append(0)
    if totems:
        found.append(1)
    if 2 in slots[n]:
        found.append(2)
    if caches:
        found.append(4)
    if 5 in slots[n]:
        found.append(5)
    return found


lines = [
    '// GENERATED by tools/gen-spancsharp.py from apworld/cw4/span_data.py.',
    '// Do not hand-edit: re-run the generator.',
    '//',
    '// The SPAN Experiments are 26 maps shipped with the game outside the Farsite',
    '// campaign. They carry mission numbers 21..46, FROZEN - location ids are',
    '// positional on the apworld side, so a renumber breaks seeds in flight.',
    'using System.Collections.Generic;',
    '',
    'namespace CW4Archipelago.Core;',
    '',
    'public static class SpanMissionTable',
    '{',
    '    /// <summary>The first SPAN mission number. Anything below this is Farsite.</summary>',
    '    public const int FirstMission = %d;' % data['FIRST_SPAN_MISSION'],
    '',
    '    /// <summary>mission -> the map guid, which IS its launch specifier.',
    '    /// Verified by booting all 26: specifier == guid on every one.</summary>',
    '    public static readonly IReadOnlyDictionary<int, string> Guids = new Dictionary<int, string>',
    '    {',
]
for n in sorted(missions):
    lines.append('        [%d] = %s,' % (n, cs_string(missions[n][0])))
lines += [
    '    };',
    '',
    '    /// <summary>mission -> title. These ARE the location-name prefixes, so a',
    '    /// change here changes every SPAN location name and every unlock item.</summary>',
    '    public static readonly IReadOnlyDictionary<int, string> Titles = new Dictionary<int, string>',
    '    {',
]
for n in sorted(missions):
    lines.append('        [%d] = %s,' % (n, cs_string(missions[n][1])))
lines += [
    '    };',
    '',
    '    /// <summary>mission -> the objective slots the MAP contains, ascending.',
    '    /// Counted from the live map, the same measurement behind the apworld',
    '    /// tables. Hold (slot 3) never appears: no Farsite mission uses it and',
    '    /// there is no location for it, so a SPAN map that has one is recorded in',
    '    /// span_data.SPAN_NOTES rather than given an objective here.</summary>',
    '    public static readonly IReadOnlyDictionary<int, int[]> Objectives = new Dictionary<int, int[]>',
    '    {',
]
for n in sorted(missions):
    obj = objectives(n)
    lines.append('        [%d] = new[] { %s },' % (n, ', '.join(str(i) for i in obj)))
lines += [
    '    };',
    '}',
    '',
]

out = '\n'.join(lines)
bad = sorted({ord(c) for c in out if ord(c) > 126})
if bad:
    sys.exit('non-ascii in generated C#: %r' % bad[:5])

old = io.open(DST, encoding='utf-8').read() if os.path.exists(DST) else None
if old == out:
    print('SpanMissionTable.g.cs unchanged (%d missions)' % len(missions))
else:
    with io.open(DST, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(out)
    print('wrote SpanMissionTable.g.cs: %d missions, %d with a Custom objective'
          % (len(missions), sum(1 for n in missions if 5 in objectives(n))))
