"""Is a seed generated by THIS apworld the same seed the old one generated?

    py -3.13 tools/parity_check.py <old.archipelago> <new.archipelago>

WHY THIS AND NOT A TEST SUITE. "The span-off tests still pass" and "a span-off
seed is unchanged" are different claims, and only the second is what a player
with the option turned off actually cares about. A change that shifted every
placement by one would pass every test in the repo and still be a different
game. So this compares two REAL generated seeds, built from the same yaml and
the same seed number, one from each side of the change.

WHAT IS COMPARED, and what a difference in each would mean:

  location ids     the id table itself. Any difference breaks seeds in flight.
  placements       location id -> (item id, player). Any difference IS a
                   different seed, even if it is still winnable.
  slot_data        the contract with the game mod. New KEYS are expected and
                   listed; a changed VALUE on an existing key is not.

Exit 0 when the seeds are identical bar the expected new slot_data keys.
"""
import os
import pickle
import sys
import zlib

# The multidata pickle references Archipelago's own classes (NetUtils and
# friends), so the clone has to be importable. Running from inside it is NOT
# enough on its own: the working directory is not on sys.path for a script
# invoked by absolute path, and without this every comparison dies with
# ModuleNotFoundError - which a harness that discards stderr reports as "the
# seed changed".
sys.path.insert(0, os.getcwd())

# STRICT MODE, for a refactor rather than a feature.
#
# The two allow-lists below exist because the SPAN change deliberately added
# slot_data keys and deliberately fixed Archon's logic. A RESTRUCTURE is
# supposed to change nothing at all, and running it against those allow-lists
# would let exactly those differences through unnoticed - the change most likely
# to be introduced by accident while moving code is a change to the tables the
# allow-lists cover.
#
# So `CW4_PARITY_STRICT=1` empties both. A pure refactor that needs an
# allow-list entry is not a pure refactor, and should fail here rather than be
# argued about later.
STRICT = os.environ.get("CW4_PARITY_STRICT") == "1"

# Keys this change is ALLOWED to add. Anything else new, or any existing key
# whose value moved, is a real difference and fails.
EXPECTED_NEW_KEYS = {
    # Added by the SPAN work, which is what this harness was built for.
    "mission_roster", "mission_titles", "span_missions",
    # Added by AUDIT 1, so the mod can notice it does not match the seed's
    # apworld. Missing from this list until 2026-09-17, which meant
    # span-off-parity.sh had reported a failure on every seed since that
    # audit and nobody had seen it - the harness is not in CI and was not
    # run again until the full sweep. The placements were identical the
    # whole time; only the key was unlisted.
    "world_version",
}

# Requirement ROWS that deliberately changed, with the reason. An allow-list that
# outlives its change is rot, so each entry says why it is here and should be
# deleted once the base commit is past it.
#
# Archon: a real logic bug, found while the SPAN work was in flight and fixed
# alongside it. Both of that mission's caches are buried and the map rains
# creeper constantly. The old rule demanded a Pylon for BOTH, which put the
# mission - and the beaten-missions count the finale needs - behind an item only
# one of them needs. The cache near the centre takes nothing but a Terp; the far
# one takes a weapon, a Terp, and either a Pylon (out of logic) or Shield plus
# Factory (in logic).
EXPECTED_CHANGED_REQUIREMENTS = {
    "Archon - Cache 1",
    "Archon - Cache 2",
    "Archon - Mission Complete",
}
REQUIREMENT_TABLES = ("location_requirements", "strict_location_requirements")

if STRICT:
    EXPECTED_NEW_KEYS = set()
    EXPECTED_CHANGED_REQUIREMENTS = set()


def load(path):
    with open(path, "rb") as fh:
        raw = fh.read()
    return pickle.loads(zlib.decompress(raw[1:]))


def slot_data_of(data):
    for _slot, sd in (data.get("slot_data") or {}).items():
        if isinstance(sd, dict):
            return sd
    return {}


def main():
    if len(sys.argv) < 3:
        print("usage: parity_check.py <old.archipelago> <new.archipelago>",
              file=sys.stderr)
        return 2
    print("  MODE  %s" % ("STRICT - nothing may differ, not even a new "
                          "slot_data key" if STRICT else
                          "feature - the allow-listed keys and rows may differ"))
    old, new = load(sys.argv[1]), load(sys.argv[2])
    bad = 0

    # --- placements ------------------------------------------------------
    # locations is {player: {location_id: (item_id, player, flags)}}.
    o_locs, n_locs = old.get("locations") or {}, new.get("locations") or {}
    o_ids = {p: set(v) for p, v in o_locs.items()}
    n_ids = {p: set(v) for p, v in n_locs.items()}
    if o_ids != n_ids:
        for p in sorted(set(o_ids) | set(n_ids)):
            only_old = o_ids.get(p, set()) - n_ids.get(p, set())
            only_new = n_ids.get(p, set()) - o_ids.get(p, set())
            if only_old or only_new:
                print("  FAIL  player %s location ids moved: %d only in old, "
                      "%d only in new" % (p, len(only_old), len(only_new)))
        bad += 1
    else:
        total = sum(len(v) for v in o_ids.values())
        print("  PASS  the same %d location ids exist" % total)

    diffs = []
    for p, table in o_locs.items():
        for loc, item in table.items():
            other = (n_locs.get(p) or {}).get(loc)
            if other != item:
                diffs.append((p, loc, item, other))
    if diffs:
        bad += 1
        print("  FAIL  %d placements differ; first few:" % len(diffs))
        for p, loc, a, b in diffs[:5]:
            print("          player %s location %s: old %s -> new %s" % (p, loc, a, b))
    else:
        print("  PASS  every item is in the same place")

    # --- slot data -------------------------------------------------------
    o_sd, n_sd = slot_data_of(old), slot_data_of(new)
    added = set(n_sd) - set(o_sd)
    removed = set(o_sd) - set(n_sd)
    changed = sorted(k for k in set(o_sd) & set(n_sd) if o_sd[k] != n_sd[k])

    unexpected = added - EXPECTED_NEW_KEYS
    if unexpected:
        bad += 1
        print("  FAIL  unexpected new slot_data keys: %s" % sorted(unexpected))
    elif added:
        print("  PASS  slot_data gained only the expected keys: %s" % sorted(added))
    else:
        print("  NOTE  slot_data gained no keys")

    if removed:
        bad += 1
        print("  FAIL  slot_data keys disappeared: %s" % sorted(removed))
    else:
        print("  PASS  no slot_data key was removed")

    # The two requirement tables are compared ROW BY ROW rather than whole, so one
    # deliberate logic fix does not mask every other row in the same table.
    hard_changed = []
    for key in changed:
        if key not in REQUIREMENT_TABLES:
            hard_changed.append(key)
            continue
        o_rows, n_rows = o_sd[key], n_sd[key]
        moved = sorted(k for k in set(o_rows) & set(n_rows) if o_rows[k] != n_rows[k])
        appeared = sorted(set(n_rows) - set(o_rows))
        vanished = sorted(set(o_rows) - set(n_rows))
        unexpected = [k for k in moved if k not in EXPECTED_CHANGED_REQUIREMENTS]
        if appeared or vanished or unexpected:
            bad += 1
            print("  FAIL  %s: %d rows changed unexpectedly, %d appeared, %d vanished"
                  % (key, len(unexpected), len(appeared), len(vanished)))
            for k in (unexpected + appeared + vanished)[:5]:
                print("          %s: old %.80s / new %.80s"
                      % (k, o_rows.get(k), n_rows.get(k)))
        else:
            print("  PASS  %s: only the %d allow-listed rows moved (%s)"
                  % (key, len(moved), ", ".join(moved)))

    if hard_changed:
        bad += 1
        print("  FAIL  %d existing slot_data keys changed value: %s"
              % (len(hard_changed), hard_changed))
        for k in hard_changed[:3]:
            print("          %s: old %.150s / new %.150s" % (k, o_sd[k], n_sd[k]))
    elif not changed:
        print("  PASS  every pre-existing slot_data key is byte-for-byte the same")

    if bad:
        print("parity: %d DIFFERENCE(S)" % bad)
    elif STRICT:
        print("parity: IDENTICAL - nothing differed at all")
    else:
        print("parity: IDENTICAL apart from the new keys")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
