using System.Collections.Generic;

namespace CW4Archipelago.Core;

/// <summary>
/// Where a mission's caches ARE, in instance order.
///
/// GENERATED by tools/gen-mapcells.py from tools/instance-dump.sh. Do not edit
/// by hand - regenerate, so the ordering rule stays the same one
/// InstanceIndex.Assign uses.
///
/// This exists because caches are the one counted objective whose instances
/// cannot be identified from live state. A nullified structure keeps standing
/// wearing IsSuppressed() and a finished totem keeps totemComplete, so both can
/// be named at any time. A collected cache is DESTROYED - measured on Farsite,
/// mustCollect 2 to 1 and the InfoCache objects in the scene 2 to 1 - and
/// UnitManager carries no id of its own, so there is nothing left to ask.
///
/// The cell IS a stable identity, though, and cache positions are MAP data:
/// they do not vary with a save, a seed or a playthrough. So rather than
/// discovering the intact set the first time the mod happens to see a mission,
/// which cannot help a save whose caches were taken before the mod was
/// installed, the set is simply known. Collected = known minus remaining.
///
/// If a game update ever moves a cache this table goes stale, which is why the
/// caller checks that what is still on the map is a SUBSET of the row before
/// trusting it, and falls back to the observed set otherwise.
/// </summary>
public static class MapCells
{
    private static readonly Dictionary<int, string[]> CacheCells = new()
    {
        [1] = new[] { "66,51", "150,63" },
        [2] = new[] { "145,91" },
        [3] = new[] { "174,42" },
        [4] = new[] { "119,28" },
        [5] = new[] { "146,74" },
        [7] = new[] { "124,59" },
        [9] = new[] { "20,103" },
        [10] = new[] { "155,92" },
        [11] = new[] { "136,72" },
        [12] = new[] { "144,53", "95,74" },
        [13] = new[] { "53,95" },
        [14] = new[] { "101,66" },
        [15] = new[] { "190,14" },
        [16] = new[] { "171,58" },
        [17] = new[] { "239,89", "89,125" },
        [18] = new[] { "95,120" },
        [19] = new[] { "31,27" },
    };

    /// <summary>A mission's cache cells in instance order, or null if unknown.</summary>
    public static IReadOnlyList<string>? CachesFor(int mission)
        => CacheCells.TryGetValue(mission, out var cells) ? cells : null;

    /// <summary>Whether every cell still on the map appears in the table. False
    /// means the table cannot be trusted for this mission - a moved cache, a
    /// modded map - and the caller must fall back rather than mislabel.</summary>
    public static bool Covers(int mission, IEnumerable<string> present)
    {
        var known = CachesFor(mission);
        if (known == null)
            return false;
        var set = new HashSet<string>(known);
        foreach (var p in present)
            if (!set.Contains(p))
                return false;
        return true;
    }
}
