// GENERATED by tools/gen_spancsharp.py from apworld/cw4/span_data.py.
// Do not hand-edit - re-run the generator.
// Do not hand-edit: re-run the generator.
//
// The SPAN Experiments are 26 maps shipped with the game outside the Farsite
// campaign. They carry mission numbers 21..46, FROZEN - location ids are
// positional on the apworld side, so a renumber breaks seeds in flight.
using System.Collections.Generic;

namespace CW4Archipelago.Core;

public static class SpanMissionTable
{
    /// <summary>The first SPAN mission number. Anything below this is Farsite.</summary>
    public const int FirstMission = 21;

    /// <summary>mission -> the map guid, which IS its launch specifier.
    /// Verified by booting all 26: specifier == guid on every one.</summary>
    public static readonly IReadOnlyDictionary<int, string> Guids = new Dictionary<int, string>
    {
        [21] = "knucracker1",
        [22] = "knucracker2",
        [23] = "knucracker3",
        [24] = "knucracker4",
        [25] = "knucracker5",
        [26] = "knucracker6",
        [27] = "knucracker7",
        [28] = "knucracker8",
        [29] = "knucracker9",
        [30] = "knucracker10",
        [31] = "knucracker11",
        [32] = "knucracker12",
        [33] = "knucracker13",
        [34] = "knucracker14",
        [35] = "knucracker15",
        [36] = "knucracker16",
        [37] = "knucracker17",
        [38] = "knucracker18",
        [39] = "knucracker19",
        [40] = "knucracker20",
        [41] = "knucrackerbonus0",
        [42] = "knucrackerbonus1",
        [43] = "demobonus",
        [44] = "demobonus2",
        [45] = "demobonus3",
        [46] = "demobonus4",
    };

    /// <summary>mission -> title. These ARE the location-name prefixes, so a
    /// change here changes every SPAN location name and every unlock item.</summary>
    public static readonly IReadOnlyDictionary<int, string> Titles = new Dictionary<int, string>
    {
        [21] = "Forgotten Fortress",
        [22] = "Four Pieces",
        [23] = "Neuron",
        [24] = "Creeper++",
        [25] = "Turtle",
        [26] = "Valley of the Shadow of Death",
        [27] = "Parasite",
        [28] = "Cheap Construction",
        [29] = "Sector L",
        [30] = "Gort",
        [31] = "Creepers Pieces",
        [32] = "Special",
        [33] = "Highway to helheim",
        [34] = "Creeperpeace",
        [35] = "Islands",
        [36] = "Enchanted Forest",
        [37] = "The Dark Side",
        [38] = "Far York Farm",
        [39] = "Chanson",
        [40] = "Invasion",
        [41] = "Razor",
        [42] = "Holdem 2",
        [43] = "Mark V Sample",
        [44] = "Before Time",
        [45] = "Day of Infamy",
        [46] = "Shaka",
    };

    /// <summary>mission -> the objective slots the MAP contains, ascending.
    /// Counted from the live map, the same measurement behind the apworld
    /// tables. Hold (slot 3) never appears: no Farsite mission uses it and
    /// there is no location for it, so a SPAN map that has one is recorded in
    /// span_data.SPAN_NOTES rather than given an objective here.</summary>
    public static readonly IReadOnlyDictionary<int, int[]> Objectives = new Dictionary<int, int[]>
    {
        [21] = new[] { 0, 1, 2 },
        [22] = new[] { 0, 1, 2 },
        [23] = new[] { 0, 1, 2 },
        [24] = new[] { 0, 1, 2 },
        [25] = new[] { 0, 1 },
        [26] = new[] { 0, 1, 2 },
        [27] = new[] { 0, 1, 2 },
        [28] = new[] { 0, 1, 2 },
        [29] = new[] { 0, 1, 2 },
        [30] = new[] { 0, 1, 2 },
        [31] = new[] { 0, 1, 2 },
        [32] = new[] { 0, 1, 2 },
        [33] = new[] { 0, 1, 2 },
        [34] = new[] { 0, 1, 2 },
        [35] = new[] { 0, 1, 2 },
        [36] = new[] { 0, 1, 2 },
        [37] = new[] { 0, 1, 2 },
        [38] = new[] { 0, 1, 2, 4 },
        [39] = new[] { 0, 1, 2, 5 },
        [40] = new[] { 0, 1, 2 },
        [41] = new[] { 0, 1, 2 },
        [42] = new[] { 0, 1, 2 },
        [43] = new[] { 0, 1 },
        [44] = new[] { 0, 1 },
        [45] = new[] { 0, 1, 2 },
        [46] = new[] { 0, 1, 2 },
    };
}
