namespace CW4Archipelago.Core;

/// <summary>Does the mod match the apworld that built this seed?
///
/// WHY THIS EXISTS. Three documents promise that the plugin and the apworld are
/// a matched pair - CHANGELOG.md's header, and docs/developing.md twice, which
/// goes as far as instructing the release notes to carry a compatibility
/// statement. Nothing enforced it anywhere but the build. No version travelled
/// in slot data, the mod read none, and the world never set
/// required_client_version, so it sat at AutoWorld's (0, 1, 6) default, which
/// passes for any client ever built.
///
/// The failure that allows is the exact one the version discipline was created
/// for, quoted in post-release-bump.yml: "a player could hold a mod and an
/// apworld agreeing on a version number and disagreeing about what the items
/// were called". A mismatched pair connected cleanly and desynchronised in
/// silence.
///
/// IT WARNS, IT DOES NOT REFUSE. A version difference is not proof of
/// incompatibility - most releases change nothing a seed depends on - and
/// refusing to connect would strand a player mid-run over a patch bump. Saying
/// so plainly, once, at the moment of connection, is what was missing.
/// </summary>
public static class VersionRules
{
    /// <summary>The message to show, or null when there is nothing to say.
    ///
    /// Null for a match, and null for an EMPTY seed version - a seed generated
    /// before the key existed carries no version, and cannot be compared. That
    /// is the common case for anything already in flight, so it must be quiet
    /// rather than alarming.
    /// </summary>
    public static string? Describe(string modVersion, string seedVersion)
    {
        if (string.IsNullOrWhiteSpace(seedVersion))
            return null;
        if (string.IsNullOrWhiteSpace(modVersion))
            return null;
        if (string.Equals(modVersion.Trim(), seedVersion.Trim(), System.StringComparison.Ordinal))
            return null;

        return $"This seed was generated by the Creeper World 4 apworld "
             + $"v{seedVersion.Trim()}, but this mod is v{modVersion.Trim()}. "
             + "They are released as a matched pair - if checks or items look "
             + "wrong, install the matching versions from the same release.";
    }

    /// <summary>Whether the two disagree, for callers that only need the flag.</summary>
    public static bool Mismatched(string modVersion, string seedVersion)
        => Describe(modVersion, seedVersion) != null;
}
